# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aec9f8c6a9a116c43f1d06b0129cf8a07340a78920397525aade549cad2af6774f55f8f07c0e5cb13d05352f2d61a0e725be51dcdd8d7fc62582bef91bdee05

test:
  secret_key_base: 3573d9a460eb590bea49c87c67edb0ec4f6c094eb41ddd93ac696725bc121c8ce8cded96e2fa374897d3b4e996d51e78ba50076a1574e827a55b3e52f17376ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
